### ISSUE TITLE
arcpy can't access files in python Flask

### ISSUE THREAD

**Issue by joeroganDOTca** [Esri/webhooks-samples#2]
Hi, I am trying to use the python Flask sample.  I've gotten the sample to work, including writing json files for each request that it receives.  The problem is as soon as I try to do anything with arcpy, it cannot access any files.  I've tried to make a really simple test of this to demonstrate what is failing, see code below.  All I'm trying to check is if my table exists in my file geodatabase.  This works outside of a Flask app environment, but not within it.  It will print False.  Any ideas why?

app = Flask(__name__)
@app.route("/", methods=["POST","GET"])
def index():
  if request.method == "GET":
    return "<h1>Hello from Webhook Listener!</h1>"
  if request.method == "POST":
    json_dict = request.get_json()
    writeJsonFile(json_dict)
    print("START")
    arcpy.env.workspace = r"\\myshare\Webhooks.gdb"
    print(arcpy.env.workspace)
    print(arcpy.Exists("all_events"))
    print("END")

**Comment by joeroganDOTca** [comment]
Just so it's clear, I tried puting my gdb at a local location c:\Webhooks\Webhooks.gdb and it still gives the same results.  If I try arcpy.Exists("all_events") in code before the Flask app stuff it will return True, but if I call that within the Flask app it will return False.

**Comment by khibma** [comment]
Hi @canadajebus - Sorry for the slow response here. Unfortunately I don't think I can help much here. From some quick google searches, there might be some issues running `arcpy` inside a server, such as Flask. (https://stackoverflow.com/questions/51292905/flask-app-with-arcgis-arcpy-does-not-run )  This might simply be an unsupported use of arcpy. You might have to run arcpy outside the web server on a scheduler to read and parse the files independently.
